# Site settings
title: Jesus Molina
description: Jesus Molina Webpage
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jesus Molina
user_description: "I am a student in the University of Texas at El Paso pursuing a masters degree in Software Engineering. I obtained my bachelor's degree in Computer Science with Cum Laude honors back in May 2016. I have been working as a Teaching Assitant in UTEP since my first semester in graduate school."
user_title: Software Engineer
email: jemonsivais@gmail.com
#twitter_username: lorem_ipsum
github_username:  jemonsivais
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
